[project]
name = "my-agent-program"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.4.2",
    "langchain-openai>=1.6.3",
    "python-dotenv>=1.2.3",
]

[project.scripts]
my-agent-program = "my_agent_program:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"
